# Generated by Django 5.0.3 on 2024-03-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sortask', '0004_task_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinvitation',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
